### ISSUE TITLE
*Enhancement: Mob Duplicator - spawn area location

### ISSUE THREAD

**Issue by dalgrim** [Buuz135/Industrial-Foregoing#145]
Modpack: Direwolf20 1.12 Version: 1.4.0
Industrial Foregoing: 1.12.2-1.6.3-107
Tesla-core-lib: 1.12-1.0.12

Right now The mob duplicator spawns mobs all around it like a vanilla spawner. However all the other mob/animal blocks in the mod feed/kill/plant/harvest in "front" or on  "top" of the block. To keep the duplicator in line with the rest of the mod why not change it to spawn on top of the block like a Plant Sower or possibly in front like a Animal Rancher/Mob Slaughter Factory/Mob Crusher. Keeping the 9x9x5 isn't a big deal as there are tons of ways to move mobs around. Having to string cables into the middle of a spawning room looks terrible though.

Regardless if you make the change, Thanks for reviving, porting and maintaining the old MFR!!

**Comment by Buuz135** [comment]
It is a bit late to change it now, maybe in 1.13

**Comment by calloatti** [comment]
With all the changes to machine ranges, maybe you could consider adding configuration options for the range and offset of the range for each machine?

**Comment by Buuz135** [comment]
I might but I don't want to overcomplicate the config.

**Comment by calloatti** [comment]
I understand not wanting to overcomplicate things, but what aspect are you concerned about?

The in-game config gui? The need to read config values for machines? Just trying to understand your line of thought to maybe suggest something.

Maybe config values with current values as defaults, not exposed in the config GUI, editable by people interested and pack makers could be a reasonable choice?

That would only leave the fact of having to read those config values instead of hard coding them.

If I am not wrong, you would only need 3 values:

radius, front/back offset and up/down offset. 

You could simplify it to radius if it seems too complicated and hard code offsets maybe?
