### ISSUE TITLE
[1.12.2-1.7.0-114] Enchantment Applicator does not work on already enchanted items

### ISSUE THREAD

**Issue by KITbutler** [Buuz135/Industrial-Foregoing#190]
Industrial Foregoing Version: 1.12.2-1.7.0-114
TeslaCoreLib Version: 1.12-1.0.12
In DW20-1.12-1.7.1 modpack via Twitch client, tested in singleplayer.

The Enchantment Applicator would appear to replace the function of the vanilla anvil, but since the recent fix it is unable to apply enchantments from books onto items which already have one or more enchantments on them. This includes combinations that are allowed by the regular anvil such as adding Fortune III to an Efficiency V diamond pickaxe.

**Comment by InterPlay02** [comment]
So, use an anvil... '-'

**Comment by Fireztonez** [comment]
There have a way to fix that and not closed without giving any reason??

I need an enchantment applicator working in my modpack, because the Vanilla Anvil is disable by Better With Mods feature and I really want to keep it like that, but now, we are stuck without any way to add an enchant to already enchanted item.

If you don't want for some reson to change that, can I have the reason??

Fireztonez

**Comment by wamc2017** [comment]
This was closed through a commit (https://github.com/Buuz135/Industrial-Foregoing/commit/2543bef50cbc10e3d4e3a9b68a5c883e737a4558) which addresses this isue...

**Comment by Buuz135** [comment]
Also, this is a 10 month issue... if it doesn't work in your modpack update the mod...

**Comment by Fireztonez** [comment]
Sorry, I have try yesterday and it look like it doesn't work with already enchanted items, but, I just try again today and it work... I probably try with incompatible enchantments without knowing it or noticing it.

So, i'm sorry for that, this is my bad, everithing work's fine!
Thank's for the reply and I have not notice the Commit number when I have write the message, so, again, my bad...

Sorry again,
Thank's for your good work and your amazing mod :)
Fireztonez
