### ISSUE TITLE
Fix "processFluidItems" sending null fluids and improve

### ISSUE THREAD

**Issue by Buuz135** [Buuz135/Industrial-Foregoing#334]
https://github.com/Buuz135/Industrial-Foregoing/blob/432e14276c69de527e1d3ed4ff7525d74b83890e/src/main/java/com/buuz135/industrial/utils/ItemStackUtils.java#L190-L209

**Comment by modmuss50** [comment]
There are still some issues with this. Let me know if you want me to open a new issue about this.

![itemsbeingmovedanyway](https://user-images.githubusercontent.com/4324090/40317881-bd95af6e-5d1a-11e8-83dc-c2035b079b2b.gif)

First issue, if the machine tries to move less fluid than the cell will accept (it only accepts 1000, and returns 0 otherwise) the cell is moved into the output slot.

![usingallfluid](https://user-images.githubusercontent.com/4324090/40317894-c2b517c8-5d1a-11e8-8b59-1e6ea03fb33f.gif)

Second issue, if there is more than 1000mb in machine all the fluid is used up, even though the cell returns that only 1000mb was used.
