### ISSUE TITLE
Potion Brewer not working when potions are stackable

### ISSUE THREAD

**Issue by MCEventHorizon** [Buuz135/Industrial-Foregoing#427]
Industrial Foregoing Version: 1.12.2-1.10.1-176
TeslaCoreLib Version: 1.12.2-1.0.14
Description: Playing Forever Stranded Lost Souls and there's a mod that makes potions stackable, because of that, Potion brewer isn't working:
![2018-09-07_11 05 55](https://user-images.githubusercontent.com/15619786/45209866-54a50080-b28e-11e8-9811-888dd2d4827d.png)

**Comment by VizuaaLOG** [comment]
@MCEventHorizon I'm also encountering this on FTB Revelations. Don't suppose you know what mod is adding stackable potions? Really need auto brewing for a project so hoping to disable it for the time being.

**Comment by Buuz135** [comment]
Quark adds that

**Comment by VizuaaLOG** [comment]
@Buuz135 Awesome, thanks I just found the config option for it as well! Very speedy reply 👍

**Comment by Buuz135** [comment]
Im still going to fix it tho

**Comment by Nividica** [comment]
Just want to note that the issue also affects the regular brewing stand as reported here:
https://github.com/Vazkii/Quark/issues/1024

And that Vazkii has since removed the option in the sourcecode:
https://github.com/Vazkii/Quark/commit/607a31025cebef22be01f6bb5eeec965285f48c7

For anyone else who finds themselves here, if editing the config is a pain you can also run the following command then restart:
`/quarkconfig tweaks "stackable items" "I:Potions" 1 save`

**Comment by JWTHDYTWA** [comment]
This issue is back in 1.20.1.
