### ISSUE TITLE
[Feature] Config Option to disable particle effects on random mobs

### ISSUE THREAD

**Issue by arcain782** [Buuz135/Industrial-Foregoing#480]
Industrial Foregoing Version:  1.11.10 (1.12.2)
TeslaCoreLib Version:  1.12.2-1.0.15
Crashlog (If Any): N/A

Screenshot: https://imgur.com/a/P2QEyot

I saw the related closed posts, but this issue has not been properly addressed. These mobs are breaking early game immersion due to what otherwise seems like a great mod to have. Not everyone wants every other sheep in their stone-age pasture to have an obnoxious eyesore indication that it may drop a rare late-game item. 

If it has to stay, at least make it so that specific particle effect can be turned off.

**Comment by arcain782** [comment]
Understood, and I saw that you said that as I read the closed posts also requesting this feature. You said the effect is indicative of something else you would not spoil relating to shiny. My biggest concern and reason for creating this issue honestly is the particle effect itself.

**Comment by Buuz135** [comment]
But why? Just because you don't like it? Don't look at it.

**Comment by arcain782** [comment]
The effect itself is neat but the way it can appear on any passive mob that players are caring for is especially distracting. It breaks immersion, especially in early game. 

Oh well It was worth a shot. You can close this and thank you for your quick response.

**Comment by Buuz135** [comment]
The mob will always have the effect is never have it... it doesnt appear on mobs randomly

**Comment by generrosity** [comment]
There does seem to be an increase of "what is this" posts on Reddit.

Would it be viable to have H/WAILA integration when looking at a mod to confirm something interesting from IF we going on?

**Comment by Luke616** [comment]
I agree with arcain, the reason why I dislike the effects is because they are both confusing to players and immersion breaking. Industrial foregoing isn't something players get into until very late game in my pack and by that point they've seen hundreds of the strange particle'd mobs and have absolutely no idea what they are for. 

Not sure where the hostility is coming from. I don't think it is unreasonable that packmakers and players would ask for an option to turn this feature off. At this point three(?) people that I've seen have taken the time to write up this request and I'm sure many others who are less vocal would like it as well.

**Comment by TheCodedOne** [comment]
Buuz has already said it's not there randomly, its not just decoration that can be turned off without side effects, and has made his decision about the config option, that's it, I'm sure HWYLA support isn't out of the question and I will be looking into that at some point, but just repeating the same thing after he's already said no isn't gonna change anything.
