### ISSUE TITLE
Plant sower interaction with Xnet

### ISSUE THREAD

**Issue by Moustik2002** [Buuz135/Industrial-Foregoing#7]
Hi,
despite the configuration i've made to let item and energy enter and exit,  plant sower seems the only block which doesn't wanna talk with xnet. Connector still desperatly not connected to sower and i've to find out an alternative way to make it work.  Could you please make relationship betweensower and connector great again  :)   ?

Here is some screenshots to describe the issue :

http://puu.sh/wkXxW/d01acba88d.jpg

http://puu.sh/wkXB3/c23c4a85a8.jpg

**Comment by Buuz135** [comment]
I know the issue, Its a thing in both ends, it could be easily fixed if the connectors checked the Side for Capabilities instead of a null side, or I could change everything in IF and break the Sideness of the machines. I have seen that ExtraUtilities works great, I imagine it checks for the side. I don't know if I can do a simple fix for it or maybe persuade McJty to change it 😛

**Comment by Moustik2002** [comment]
but what's the difference  betweeen sower and other IF machines ?

**Comment by Buuz135** [comment]
Machines that connect have a tank and the ones that doesnt it wont connect.
